### ISSUE TITLE
Jetstream 4 Support

### ISSUE THREAD

**Issue by Supernova3339** [joelbutcher/jetstream-team-transfer#15]
Could you add Jetstream 4 support for this? Would be awesome, @joelbutcher !

**Comment by joelbutcher** [comment]
Currently working on this - I can't give you a release date unfortunately.

**Comment by Supernova3339** [comment]
> Currently working on this - I can't give you a release date unfortunately. I'm also adding support for the inertia stack with this release! 🔥

Awesome!
