### ISSUE TITLE
Team transfer logic

### ISSUE THREAD

**Issue by iantasker** [joelbutcher/jetstream-team-transfer#4]
After reviewing the `TransferTeam` code it looks like you can transfer the team to any user within the system, this could cause an issue if the user is not a member of the team.

Wouldn't it be better to select a team user (with admin or config set role) from the list like this? 

![image](https://user-images.githubusercontent.com/17986190/104903394-d7b6e500-5977-11eb-9367-1209ce5f240c.png)

**Comment by joelbutcher** [comment]
@iantasker I initially added a similar button to the list of users in the team member manager component in a PR to Jestream v2, but [it got rejected](https://github.com/laravel/jetstream/pull/526) - hence the reason for this package.

I'm not adversed to switching up the logic for v2 here. I think to avoid a bottomless list here a searchable select of user names + emails might be a better UX? 

Open to discussion & PR's around this 😎

**Comment by joelbutcher** [comment]
@iantasker I've created a PR that should fix the issue on 1.x - can you take a look?
