### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by Supernova3339** [joelbutcher/jetstream-team-transfer#7]
Hi, this package looks awesome and looking to integrate this. However, there's some problems that should  be addressed.

This package does not support Laravel 10 ( Illuminate\Support )

**Comment by joelbutcher** [comment]
@Supernova3339 this has been added in [2.x today](https://github.com/joelbutcher/jetstream-team-transfer/releases/tag/v2.0.0) – thanks for the spot!

**Comment by Supernova3339** [comment]
Thanks for the swift addition, Joel!
